;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.0
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cffi:defcfun ("eb_set_binary_mono_graphic" eb_set_binary_mono_graphic) :pointer
  (book :pointer)
  (position :pointer)
  (width :int)
  (height :int))

(cffi:defcfun ("eb_set_binary_gray_graphic" eb_set_binary_gray_graphic) :pointer
  (book :pointer)
  (position :pointer)
  (width :int)
  (height :int))

(cffi:defcfun ("eb_set_binary_wave" eb_set_binary_wave) :pointer
  (book :pointer)
  (start_position :pointer)
  (end_position :pointer))

(cffi:defcfun ("eb_set_binary_color_graphic" eb_set_binary_color_graphic) :pointer
  (book :pointer)
  (position :pointer))

(cffi:defcfun ("eb_set_binary_mpeg" eb_set_binary_mpeg) :pointer
  (book :pointer)
  (argv :pointer))

(cffi:defcfun ("eb_read_binary" eb_read_binary) :pointer
  (book :pointer)
  (binary_max_length :pointer)
  (binary :string)
  (binary_length :pointer))

(cffi:defcfun ("eb_unset_binary" eb_unset_binary) :void
  (book :pointer))

(cffi:defcfun ("eb_compose_movie_file_name" eb_compose_movie_file_name) :pointer
  (argv :pointer)
  (composed_file_name :string))

(cffi:defcfun ("eb_compose_movie_path_name" eb_compose_movie_path_name) :pointer
  (book :pointer)
  (argv :pointer)
  (composed_path_name :string))

(cffi:defcfun ("eb_decompose_movie_file_name" eb_decompose_movie_file_name) :pointer
  (argv :pointer)
  (composed_file_name :string))


